### ISSUE TITLE
Week temperatures too low

### ISSUE THREAD

**Issue by MichaelMcDonnell** [SecUSo/privacy-friendly-weather#96]
The temperatures in the weekly overview are too low. I expected it to have the daily high. It does not have the daily high here in California.

I suspect the issue is similar to issue #93. I suspect a time is picked to show the temperature for, and sometime during the middle of the night is chosen instead of the warmest time of day. I haven't looked at the code so I cannot say for sure. I would have expected the code to just look at all the temperatures for the day and pick the highest one.

![Screenshot_20200625-062715](https://user-images.githubusercontent.com/20253/85729723-e5d8a780-b6ad-11ea-8df8-e6ec9a333b6f.png)

**Comment by MichaelMcDonnell** [comment]
![Screenshot_20200625-062715](https://user-images.githubusercontent.com/20253/85729723-e5d8a780-b6ad-11ea-8df8-e6ec9a333b6f.png)

**Comment by MichaelMcDonnell** [comment]
I just got the latest master and the daily highs are much closer to the expected values. However, they are still at least a few 4-5 F lower than openweathermap.com and weather.com.

**Comment by MichaelMcDonnell** [comment]
I figured out why the temperature is slightly too low for the course of the week. The following code in `CityWeatherData.java` assumes the hottest time of day is after 10 and before 14:

```java
//TODO replace with max and min values for the days
if (c.get(Calendar.HOUR_OF_DAY) < 14 && c.get(Calendar.HOUR_OF_DAY) > 10) {
    forecastList.add(f);
}
```

The hottest time of the day is usually around 15. I can make it closer by adjusting the times, e.g:

```java
//TODO replace with max and min values for the days
if (c.get(Calendar.HOUR_OF_DAY) < 17 && c.get(Calendar.HOUR_OF_DAY) > 13) {
    forecastList.add(f);
}
```

That is still a hack because there might be a rain storm during those hours. The correct solution is already proposed in the TODO comment. The maximum temperature should be found instead.

**Comment by sleep-yearning** [comment]
Hey, you are too fast! :D
I haven't pushed the latest commits yet, where the issue is resolved better. 
The temperatures don't reflect _exactly_ the same as OWM because the interval is only 3hours but it's pretty much the same.

**Comment by sleep-yearning** [comment]
Should be fixed with b5410e8e8ea783a472bcbf4893fb8984c82596df

**Comment by MichaelMcDonnell** [comment]
Hi @sleep-yearning I got the latest master and the temperatures for the course of the week are still buggy but in a new way. Do you want me to open a new bug or are you re-opening this one?

Thursday (today) appears twice in the screenshot. The temperatures are also wrong. It is not going to be 97.6 F Thursday (today), it is only going to be around 89 F. Friday is going to be 98 F and not 93 F. So something is unfortunately not right.

![Screenshot_20200813-114610](https://user-images.githubusercontent.com/20253/90175526-689beb80-dd5c-11ea-8328-e736998cd9e5.png)

**Comment by sleep-yearning** [comment]
That's interesting. The double days should be fixed by now, the temperature errors seem like forecasts get assigned to the wrong day. Or the days being shifted by one. That's just what it sounds like from your example. 
However, I also changed some parts of the timing calculations. 
Please try again with the latest build. :)

**Comment by MichaelMcDonnell** [comment]
Latest build looks good to me!
